version: 0.2

phases:
  pre_build:
    commands:
      - ls -l
      - aws sts get-caller-identity
      - aws assume-role --role-arn arn:aws:iam::654654492738:role/temp-s3-build-role --role-session-name s3-access-example
      - echo "Moving to Animated Landing Page Website Template directory..."
      - mv "Animated Landing Page Website Template" animated-landing-page
      - cd animated-landing-page
      - ls -l
      - AWS_REGION="ap-northeast-2" # 실제 AWS 리전으로 변경하세요 (예: ap-northeast-2)
      - S3_BUCKET_NAME="abc-dev-roro-static-s3" # 실제 S3 버킷 이름으로 변경하세요
      - DISTRIBUTION_ID="E2YBK4I3DJPC0Z" # 실제 CloudFront 배포 ID로 변경하세요

  build:
    commands:
      - echo "Uploading files to S3..."
      - echo $S3_BUCKET_NAME
      - aws s3 sync . s3://$S3_BUCKET_NAME

  post_build:
    commands:
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
      - echo "CloudFront cache invalidation initiated."

artifacts:
  files:
    - '**/*'
  base-directory: "Animated Landing Page Website Template"
  discard-paths: yes
